# THIS IS THE FILE YOU UPDATE IF YOU NEED TO ADD A NEW FIELD
# MAKE SURE TO ADD IT TO THE CSV_FIELDS AND CSV_ROWS IN THE *SAME RELATIVE LOCATION*
csv_fields = [
    "time",
    "state",
    "loadCell",
    "kerInletDucer",
    # "kerN2Ducer",
    "pneumaticDucer",
    "kerPintleDucer",
    "kerTankDucer",
    "kerVenturi",
    "loxInletDucer",
    # "loxN2Ducer",
    "loxTankDucer",
    "loxVenturi",
    "purgeDucer",
    "manifoldInletThermo",
    "manifoldOutletThermo",
    "tank1Thermo",
    "tank2Thermo",
    "tank3Thermo",
    "kerDrip",
    "kerFlow",
    "kerPressurant",
    "kerPurge",
    "kerVent",
    "loxDrip",
    "loxFlow",
    "loxPressurant",
    "loxPurge",
    "loxVent",
    "loxRegDucer" "kerRegDucer",
]


def get_json_rows(msg_json):
    csv_row = {
        "time": msg_json["timeStamp"],
        "state": msg_json["currentState"],
        "loadCell": msg_json["data"]["loadCellSensors"]["loadCell"]["sensorReading"],
        "kerInletDucer": msg_json["data"]["pressureSensors"]["kerInletDucer"]["sensorReading"],
        "kerN2Ducer": msg_json["data"]["pressureSensors"]["kerN2Ducer"]["sensorReading"],
        "pneumaticDucer": msg_json["data"]["pressureSensors"]["pneumaticDucer"]["sensorReading"],
        "kerPintleDucer": msg_json["data"]["pressureSensors"]["kerPintleDucer"]["sensorReading"],
        "kerTankDucer": msg_json["data"]["pressureSensors"]["kerTankDucer"]["sensorReading"],
        "kerVenturi": msg_json["data"]["pressureSensors"]["kerVenturi"]["sensorReading"],
        "loxInletDucer": msg_json["data"]["pressureSensors"]["loxInletDucer"]["sensorReading"],
        "loxN2Ducer": msg_json["data"]["pressureSensors"]["loxN2Ducer"]["sensorReading"],
        "loxTankDucer": msg_json["data"]["pressureSensors"]["loxTankDucer"]["sensorReading"],
        "loxVenturi": msg_json["data"]["pressureSensors"]["loxVenturi"]["sensorReading"],
        "purgeDucer": msg_json["data"]["pressureSensors"]["purgeDucer"]["sensorReading"],
        "loxRegDucer": msg_json["data"]["pressureSensors"]["loxRegDucer"]["sensorReading"],
        "kerRegDucer": msg_json["data"]["pressureSensors"]["kerRegDucer"]["sensorReading"],
        "manifoldInletThermo": msg_json["data"]["tempSensors"]["manifoldInletThermo"]["sensorReading"],
        "manifoldOutletThermo": msg_json["data"]["tempSensors"]["manifoldOutletThermo"]["sensorReading"],
        "tank1Thermo": msg_json["data"]["tempSensors"]["tank1Thermo"]["sensorReading"],
        "tank2Thermo": msg_json["data"]["tempSensors"]["tank2Thermo"]["sensorReading"],
        "tank3Thermo": msg_json["data"]["tempSensors"]["tank3Thermo"]["sensorReading"],
        "kerDrip": msg_json["data"]["valves"]["kerDrip"]["valveState"],
        "kerFlow": msg_json["data"]["valves"]["kerFlow"]["valveState"],
        "kerPressurant": msg_json["data"]["valves"]["kerPressurant"]["valveState"],
        "kerPurge": msg_json["data"]["valves"]["kerPurge"]["valveState"],
        "kerVent": msg_json["data"]["valves"]["kerVent"]["valveState"],
        "loxDrip": msg_json["data"]["valves"]["loxDrip"]["valveState"],
        "loxFlow": msg_json["data"]["valves"]["loxFlow"]["valveState"],
        "loxPressurant": msg_json["data"]["valves"]["loxPressurant"]["valveState"],
        "loxPurge": msg_json["data"]["valves"]["loxPurge"]["valveState"],
        "loxVent": msg_json["data"]["valves"]["loxVent"]["valveState"],
    }
    return csv_row
